#!/bin/bash

if [ -z "$1" ]; then
	echo "No arguments provided!"
	exit 1
fi

mkdir $1
cd $1
cp ../README.md .
cp ../commit .
mkdir ilahe
cd ilahe
git clone https://github.com/aysucuk/holbertonschool-higher_level_programming
cd holbertonschool-higher_level_programming
cd $1
find -type f ! -name "*.py" ! -name "*.txt" -exec rm {} \;
mv * ../../../
cd ../../../
rm -rf ilahe
./commit
