-- bashi
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY
FROM information_schem.COLUMNS
WHERE TABLE_SCHEMA = 'hbtn_0c_0 ' AND TABLE_NAME = 'first_table';
